# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["complexnet.py"]

doc_url = "https://keepsimpler.github.io/hong/"

git_url = "https://github.com/keepsimpler/hong/tree/master/"

def custom_doc_links(name): return None
