# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"cascade": "00_graph.ipynb",
         "after_DAG": "00_graph.ipynb",
         "xception_block": "01_complexnet.ipynb",
         "complex_net": "01_complexnet.ipynb",
         "complexnet_1": "01_complexnet.ipynb",
         "complex_stage": "01_complexnet.ipynb",
         "complexnet_2": "01_complexnet.ipynb"}

modules = ["graph.py",
           "complexnet.py"]

doc_url = "https://keepsimpler.github.io/hong/"

git_url = "https://github.com/keepsimpler/hong/tree/master/"

def custom_doc_links(name): return None
